### ISSUE TITLE
Netbeans 8.2

### ISSUE THREAD

**Issue by hartundweich** [dfranek/NetBeans-TypoScript#22]
Netbeans 8.2 is out for a while - is there a plan to migrate this plugin to netbeans 8.2?

**Comment by dfranek** [comment]
Hi,

I moved recently, so I didn't have time for the plugin. I will release a a compatible Version within the next week.

**Comment by Oktopuce** [comment]
Hi,

I don't understand how to install this version on NetBeans 8.2.
I tried to install it from here http://plugins.netbeans.org/plugin/41543/typoscript-support-for-netbeans-ide but there is only a version for Netbeans 8.1 and nothing happen when I open a typoscript file.
How can I install the current version ?
What are the extension used with this plugin : .txt, .ts ?

Thx,
Florian

**Comment by dfranek** [comment]
Hi,

excuse my late answer. Unfortunately I can't upload a version for 8.2 at the moment because i can not selct this version in the Plugin Portal.

Could you try the file attached to this issue (unzip first)?
[net-dfranek-typoscript.zip](https://github.com/dfranek/NetBeans-TypoScript/files/851566/net-dfranek-typoscript.zip)

**Comment by Oktopuce** [comment]
Thx for your reply but it's ok it works now.

**Comment by koehnlein** [comment]
Thanks for your work! The 8.2 version of your plugins works for me.

It would be great, if you could add the download to the official plugin page. It took a few minutes to find it. ;-)
