### ISSUE TITLE
enable adding individual file extensions or please add .typoscript file extension

### ISSUE THREAD

**Issue by webcande** [dfranek/NetBeans-TypoScript#24]
Great plugin, Daniel. I put a link in TYPO3 slack channel. Hope, you get more attention. 

As new TypoScript file endings are introduced https://github.com/TYPO3/TYPO3.CMS/commit/09a610277ea2de1946e2e8ccdfdb39cd9196cf1f, I wonder if it is possible to enable adding individual file endings, so you have not to bother around with all these questions (saw a closed issue) and developers can add what they want. 

If not, how about adding .typoscript file extension?

And here you can check the decision process, if you need some more information about this topic: https://decisions.typo3.org/t/file-endings-for-typoscript-files-and-tsconfig-files/43/14

**Comment by dfranek** [comment]
I created a new version with support for .typoscript and removed the support for .ts. Adding individual file extensions is a default feature of NetBeans. You can do it under Options -> Miscellaneous -> Files. There you have to add a new entry and choose text/x-typoscript under "Associated File Type (MIME)".

The new Plugin Version is available here:
[net-dfranek-typoscript.zip](https://github.com/dfranek/NetBeans-TypoScript/files/1309215/net-dfranek-typoscript.zip)

I will try to upload it to the Plugin Portal, but at the moment I'm not able to upload a new binary because of a bug in the portal.

**Comment by webcande** [comment]
Hi Daniel,

thank you very much.

Greetings

Erdal
